name: GitHub CI

on:
  push:
  pull_request:


jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest]
        java: [11, 17]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3.4.1
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: 'maven'
          
      - name: Build with Maven
        run: mvn -e  -B -V install -Pci-build -T2
